using HumanOS.SimulationLabs.Api.Features.AiLabBuilder;

namespace HumanOS.SimulationLabs.Api.Features.AiLabBuilder.Contracts;

/// <summary>A simulated actor the agent proposes for the scenario (one or several).</summary>
public sealed class ActorDraft
{
    /// <summary>Draft-local reference, e.g. "ACT_1". Not a database id — nothing is persisted yet.</summary>
    public string Ref { get; set; } = string.Empty;

    public string Role { get; set; } = string.Empty;

    /// <summary>DIRECT, COLLABORATIVE, RESERVED, SKEPTICAL, IMPATIENT, DETAIL_ORIENTED or EXECUTIVE.</summary>
    public string CommunicationStyle { get; set; } = string.Empty;

    public bool IsPrincipal { get; set; }

    public string Description { get; set; } = string.Empty;
}

public sealed class StageDraft
{
    public string Ref { get; set; } = string.Empty;

    public int Order { get; set; }

    public string Name { get; set; } = string.Empty;

    public string Description { get; set; } = string.Empty;
}

public sealed class ObjectiveDraft
{
    public string Ref { get; set; } = string.Empty;

    public string StageRef { get; set; } = string.Empty;

    public string Description { get; set; } = string.Empty;

    public decimal Weight { get; set; }

    public bool IsCritical { get; set; }
}

public sealed class DialogueDraft
{
    public string Ref { get; set; } = string.Empty;

    public string StageRef { get; set; } = string.Empty;

    public string ObjectiveRef { get; set; } = string.Empty;

    public string ActorRef { get; set; } = string.Empty;

    public int Order { get; set; }

    public string ActorSays { get; set; } = string.Empty;

    public string ExpectedIntent { get; set; } = string.Empty;

    public string ExemplaryResponse { get; set; } = string.Empty;

    public string FrequentError { get; set; } = string.Empty;

    public string Recommendation { get; set; } = string.Empty;

    public string SkillEvaluated { get; set; } = string.Empty;

    public bool IsCritical { get; set; }
}

public sealed class CriterionDraft
{
    public string Ref { get; set; } = string.Empty;

    public string ObjectiveRef { get; set; } = string.Empty;

    public string? MomentRef { get; set; }

    public string Name { get; set; } = string.Empty;

    public string Description { get; set; } = string.Empty;

    public decimal Weight { get; set; }

    public decimal MinScore { get; set; }

    public string PositiveIndicators { get; set; } = string.Empty;

    public string NegativeIndicators { get; set; } = string.Empty;

    public bool IsCritical { get; set; }
}

public sealed class TestedSkillDraft
{
    public string SkillName { get; set; } = string.Empty;

    /// <summary>"TECHNICAL" or "SOFT".</summary>
    public string SkillType { get; set; } = "TECHNICAL";

    /// <summary>Why this skill is relevant for this specific role and scenario.</summary>
    public string RelevanceToRole { get; set; } = string.Empty;

    /// <summary>Observable benchmark standard of what high performance looks like in this simulation.</summary>
    public string DemonstrationStandard { get; set; } = string.Empty;

    /// <summary>List of dialogue/moment refs or order numbers where this skill is tested (e.g. ["#1", "#4"]).</summary>
    public List<string> TestedInMoments { get; set; } = [];

    /// <summary>Ref of the rubric criterion evaluating this skill (e.g. "CRT_1").</summary>
    public string? RubricCriterionRef { get; set; }

    /// <summary>Formative feedback guidance to give the real student when demonstrating or failing this skill.</summary>
    public string FeedbackGuidance { get; set; } = string.Empty;
}

/// <summary>The full reusable Lab draft content generated by the AI Lab Builder agent. Nothing here is persisted.</summary>
public sealed class LabDraftContent
{
    /// <summary>Only populated when the caller left LabName empty — the agent's proposed name
    /// for this Lab, inferred from the process/role/skills. Ignored otherwise.</summary>
    public string? SuggestedLabName { get; set; }

    public string LabDescription { get; set; } = string.Empty;

    public string ScenarioProblemaCentral { get; set; } = string.Empty;

    public string ScenarioResultadoEsperado { get; set; } = string.Empty;

    public List<TestedSkillDraft> TestedSkills { get; set; } = [];

    public List<ActorDraft> Actors { get; set; } = [];

    public List<StageDraft> Stages { get; set; } = [];

    public List<ObjectiveDraft> Objectives { get; set; } = [];

    public List<DialogueDraft> Dialogues { get; set; } = [];

    public List<CriterionDraft> Criteria { get; set; } = [];
}

/// <summary>Structured output requested from the LLM: either a complete draft, or a request for missing information.</summary>
public sealed class LabDraftGenerationResult
{
    public bool NeedsInformation { get; set; }

    public List<string> Questions { get; set; } = [];

    public LabDraftContent? Draft { get; set; }
}

/// <summary>HTTP response returned to the human reviewer. No database ids — nothing has been saved yet.</summary>
public sealed class GenerateLabDraftResponse
{
    public string Status { get; set; } = string.Empty;

    public string? LabName { get; set; }

    public string? TargetRole { get; set; }

    public string? Language { get; set; }

    public string? Difficulty { get; set; }

    public decimal? ScoreMinimo { get; set; }

    public LabDraftContent? Draft { get; set; }

    public List<string> Questions { get; set; } = [];

    public List<string> Warnings { get; set; } = [];

    public bool HumanReviewRequired { get; set; } = true;

    public string CorrelationId { get; set; } = string.Empty;

    /// <summary>Tokens, timing and estimated USD cost of this generation call (not persisted).</summary>
    public LabBuilderCostEstimate? Cost { get; set; }
}
