// <auto-generated />
using System;
using HumanOS.SimulationLabs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanOS.SimulationLabs.Migrations
{
    [DbContext(typeof(SimulationLabsDbContext))]
    [Migration("20260912154933_CreateLabVersionTable")]
    partial class CreateLabVersionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Lab", b =>
                {
                    b.Property<Guid>("LAB_IdLab")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LAB_Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LAB_Descripcion")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAB_Dominio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LAB_Estatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LAB_Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("LAB_OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LAB_Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SEG_IdTenant")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LAB_IdLab");

                    b.HasAlternateKey("SEG_IdTenant", "LAB_IdLab")
                        .HasName("AK_LAB_Lab_SEG_IdTenant_LAB_IdLab");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_Estatus" }, "IX_LAB_Lab_SEG_IdTenant_LAB_Estatus");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_Codigo" }, "UQ_LAB_Lab_SEG_IdTenant_LAB_Codigo")
                        .IsUnique();

                    b.ToTable("LAB_Lab", null, t =>
                        {
                            t.HasCheckConstraint("CK_LAB_Lab_LAB_Estatus", "[LAB_Estatus] IN ('DRAFT', 'PUBLISHED', 'RETIRED')");

                            t.HasCheckConstraint("CK_LAB_Lab_LAB_Tipo", "[LAB_Tipo] IN ('CONVERSATIONAL', 'DESKTOP', 'HYBRID')");
                        });
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_LabVersion", b =>
                {
                    b.Property<Guid>("LAB_IdVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LAB_BriefOculto")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LAB_DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("LAB_Estatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LAB_HashConfiguracion")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<Guid>("LAB_IdLab")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LAB_InstruccionesParticipante")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LAB_NumeroVersion")
                        .HasColumnType("int");

                    b.Property<string>("LAB_ObjetivoGeneral")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LAB_ScoreMinimo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("LAB_VigenciaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LAB_VigenciaHasta")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SEG_IdTenant")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LAB_IdVersion");

                    b.HasIndex(new[] { "LAB_IdLab" }, "IX_LAB_LabVersion_LAB_IdLab");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdLab" }, "IX_LAB_LabVersion_SEG_IdTenant_LAB_IdLab");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdLab", "LAB_Estatus" }, "IX_LAB_LabVersion_SEG_IdTenant_LAB_IdLab_LAB_Estatus");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_Estatus", "LAB_VigenciaDesde", "LAB_VigenciaHasta" }, "IX_LAB_LabVersion_Tenant_Estatus_Vigencias");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdLab", "LAB_NumeroVersion" }, "UQ_LAB_LabVersion_SEG_IdTenant_LAB_IdLab_LAB_NumeroVersion")
                        .IsUnique();

                    b.ToTable("LAB_LabVersion", null, t =>
                        {
                            t.HasCheckConstraint("CK_LAB_LabVersion_LAB_DuracionMinutos", "[LAB_DuracionMinutos] > 0");

                            t.HasCheckConstraint("CK_LAB_LabVersion_LAB_Estatus", "[LAB_Estatus] IN ('DRAFT', 'APPROVED', 'PUBLISHED', 'RETIRED')");

                            t.HasCheckConstraint("CK_LAB_LabVersion_LAB_HashConfiguracion", "([LAB_HashConfiguracion] IS NULL) OR (LEN([LAB_HashConfiguracion]) = 64)");

                            t.HasCheckConstraint("CK_LAB_LabVersion_LAB_NumeroVersion", "[LAB_NumeroVersion] > 0");

                            t.HasCheckConstraint("CK_LAB_LabVersion_LAB_ScoreMinimo", "[LAB_ScoreMinimo] >= 1.00 AND [LAB_ScoreMinimo] <= 10.00");

                            t.HasCheckConstraint("CK_LAB_LabVersion_Vigencia", "([LAB_VigenciaHasta] IS NULL) OR ([LAB_VigenciaDesde] IS NULL) OR ([LAB_VigenciaHasta] >= [LAB_VigenciaDesde])");
                        });
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_LabVersion", b =>
                {
                    b.HasOne("HumanOS.SimulationLabs.Entities.LAB_Lab", "Lab")
                        .WithMany("Versiones")
                        .HasForeignKey("SEG_IdTenant", "LAB_IdLab")
                        .HasPrincipalKey("SEG_IdTenant", "LAB_IdLab")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LAB_LabVersion_LAB_Lab_SEG_IdTenant_LAB_IdLab");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Lab", b =>
                {
                    b.Navigation("Versiones");
                });
#pragma warning restore 612, 618
        }
    }
}
