// <auto-generated />
using System;
using HumanOS.SimulationLabs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanOS.SimulationLabs.Migrations
{
    [DbContext(typeof(SimulationLabsDbContext))]
    [Migration("20260912165702_CreateLabRubricCriterionTable")]
    partial class CreateLabRubricCriterionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_ExpectedMoment", b =>
                {
                    b.Property<Guid>("MOM_IdExpectedMoment")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LAB_IdVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MOM_Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("MOM_ErrorFrecuente")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MOM_EsCritico")
                        .HasColumnType("bit");

                    b.Property<string>("MOM_Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("DRAFT");

                    b.Property<string>("MOM_InformacionDescubrible")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOM_IntencionEsperada")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOM_Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MOM_OrdenSugerido")
                        .HasColumnType("int");

                    b.Property<bool>("MOM_PermiteOrdenFlexible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MOM_Recomendacion")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MOM_RequiereRespuesta")
                        .HasColumnType("bit");

                    b.Property<string>("MOM_RespuestaEjemplar")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOM_Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MOM_Trigger")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OBJ_IdObjective")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SEG_IdTenant")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("STG_IdStage")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MOM_IdExpectedMoment");

                    b.HasAlternateKey("SEG_IdTenant", "LAB_IdVersion", "MOM_IdExpectedMoment")
                        .HasName("AK_LAB_ExpectedMoment_SEG_IdTenant_LAB_IdVersion_MOM_IdExpectedMoment");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion" }, "IX_LAB_ExpectedMoment_SEG_IdTenant_LAB_IdVersion");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "OBJ_IdObjective" }, "IX_LAB_ExpectedMoment_Tenant_Version_Objective");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "STG_IdStage" }, "IX_LAB_ExpectedMoment_Tenant_Version_Stage");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "STG_IdStage", "MOM_EsCritico" }, "IX_LAB_ExpectedMoment_Tenant_Version_Stage_EsCritico");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "STG_IdStage", "MOM_Estatus" }, "IX_LAB_ExpectedMoment_Tenant_Version_Stage_Estatus");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "MOM_Codigo" }, "UQ_LAB_ExpectedMoment_SEG_IdTenant_LAB_IdVersion_MOM_Codigo")
                        .IsUnique();

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "STG_IdStage", "MOM_OrdenSugerido" }, "UQ_LAB_ExpectedMoment_Tenant_Version_Stage_Orden")
                        .IsUnique();

                    b.ToTable("LAB_ExpectedMoment", null, t =>
                        {
                            t.HasCheckConstraint("CK_LAB_ExpectedMoment_CreadoPor", "LEN(TRIM([CreadoPor])) > 0");

                            t.HasCheckConstraint("CK_LAB_ExpectedMoment_MOM_Codigo", "LEN(TRIM([MOM_Codigo])) > 0");

                            t.HasCheckConstraint("CK_LAB_ExpectedMoment_MOM_Estatus", "[MOM_Estatus] IN ('DRAFT', 'ACTIVE', 'INACTIVE')");

                            t.HasCheckConstraint("CK_LAB_ExpectedMoment_MOM_IntencionEsperada", "LEN(TRIM([MOM_IntencionEsperada])) > 0");

                            t.HasCheckConstraint("CK_LAB_ExpectedMoment_MOM_Nombre", "LEN(TRIM([MOM_Nombre])) > 0");

                            t.HasCheckConstraint("CK_LAB_ExpectedMoment_MOM_OrdenSugerido", "[MOM_OrdenSugerido] > 0");

                            t.HasCheckConstraint("CK_LAB_ExpectedMoment_MOM_Tipo", "[MOM_Tipo] IN ('DIALOGUE', 'USER_ACTION', 'SYSTEM_EVENT', 'DECISION_POINT', 'ARTIFACT_REVIEW')");

                            t.HasCheckConstraint("CK_LAB_ExpectedMoment_MOM_Trigger", "LEN(TRIM([MOM_Trigger])) > 0");
                        });
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Lab", b =>
                {
                    b.Property<Guid>("LAB_IdLab")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LAB_Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LAB_Descripcion")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAB_Dominio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LAB_Estatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LAB_Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("LAB_OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LAB_Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SEG_IdTenant")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LAB_IdLab");

                    b.HasAlternateKey("SEG_IdTenant", "LAB_IdLab")
                        .HasName("AK_LAB_Lab_SEG_IdTenant_LAB_IdLab");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_Estatus" }, "IX_LAB_Lab_SEG_IdTenant_LAB_Estatus");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_Codigo" }, "UQ_LAB_Lab_SEG_IdTenant_LAB_Codigo")
                        .IsUnique();

                    b.ToTable("LAB_Lab", null, t =>
                        {
                            t.HasCheckConstraint("CK_LAB_Lab_LAB_Estatus", "[LAB_Estatus] IN ('DRAFT', 'PUBLISHED', 'RETIRED')");

                            t.HasCheckConstraint("CK_LAB_Lab_LAB_Tipo", "[LAB_Tipo] IN ('CONVERSATIONAL', 'DESKTOP', 'HYBRID')");
                        });
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_LabVersion", b =>
                {
                    b.Property<Guid>("LAB_IdVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LAB_BriefOculto")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LAB_DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("LAB_Estatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LAB_HashConfiguracion")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<Guid>("LAB_IdLab")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LAB_InstruccionesParticipante")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LAB_NumeroVersion")
                        .HasColumnType("int");

                    b.Property<string>("LAB_ObjetivoGeneral")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LAB_ScoreMinimo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("LAB_VigenciaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LAB_VigenciaHasta")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SEG_IdTenant")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LAB_IdVersion");

                    b.HasAlternateKey("SEG_IdTenant", "LAB_IdVersion")
                        .HasName("AK_LAB_LabVersion_SEG_IdTenant_LAB_IdVersion");

                    b.HasIndex(new[] { "LAB_IdLab" }, "IX_LAB_LabVersion_LAB_IdLab");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdLab" }, "IX_LAB_LabVersion_SEG_IdTenant_LAB_IdLab");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdLab", "LAB_Estatus" }, "IX_LAB_LabVersion_SEG_IdTenant_LAB_IdLab_LAB_Estatus");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_Estatus", "LAB_VigenciaDesde", "LAB_VigenciaHasta" }, "IX_LAB_LabVersion_Tenant_Estatus_Vigencias");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdLab", "LAB_NumeroVersion" }, "UQ_LAB_LabVersion_SEG_IdTenant_LAB_IdLab_LAB_NumeroVersion")
                        .IsUnique();

                    b.ToTable("LAB_LabVersion", null, t =>
                        {
                            t.HasCheckConstraint("CK_LAB_LabVersion_LAB_DuracionMinutos", "[LAB_DuracionMinutos] > 0");

                            t.HasCheckConstraint("CK_LAB_LabVersion_LAB_Estatus", "[LAB_Estatus] IN ('DRAFT', 'APPROVED', 'PUBLISHED', 'RETIRED')");

                            t.HasCheckConstraint("CK_LAB_LabVersion_LAB_HashConfiguracion", "([LAB_HashConfiguracion] IS NULL) OR (LEN([LAB_HashConfiguracion]) = 64)");

                            t.HasCheckConstraint("CK_LAB_LabVersion_LAB_NumeroVersion", "[LAB_NumeroVersion] > 0");

                            t.HasCheckConstraint("CK_LAB_LabVersion_LAB_ScoreMinimo", "[LAB_ScoreMinimo] >= 1.00 AND [LAB_ScoreMinimo] <= 10.00");

                            t.HasCheckConstraint("CK_LAB_LabVersion_Vigencia", "([LAB_VigenciaHasta] IS NULL) OR ([LAB_VigenciaDesde] IS NULL) OR ([LAB_VigenciaHasta] >= [LAB_VigenciaDesde])");
                        });
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Objective", b =>
                {
                    b.Property<Guid>("OBJ_IdObjective")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LAB_IdVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OBJ_Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OBJ_CondicionExito")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBJ_Descripcion")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OBJ_EsCritico")
                        .HasColumnType("bit");

                    b.Property<string>("OBJ_Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("DRAFT");

                    b.Property<int>("OBJ_Orden")
                        .HasColumnType("int");

                    b.Property<decimal>("OBJ_Peso")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<string>("OBJ_TipoEvidencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SEG_IdTenant")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("STG_IdStage")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OBJ_IdObjective");

                    b.HasAlternateKey("SEG_IdTenant", "LAB_IdVersion", "OBJ_IdObjective")
                        .HasName("AK_LAB_Objective_SEG_IdTenant_LAB_IdVersion_OBJ_IdObjective");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "OBJ_EsCritico" }, "IX_LAB_Objective_SEG_IdTenant_LAB_IdVersion_OBJ_EsCritico");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "OBJ_Estatus" }, "IX_LAB_Objective_SEG_IdTenant_LAB_IdVersion_OBJ_Estatus");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "STG_IdStage", "OBJ_Orden" }, "IX_LAB_Objective_Tenant_Version_Stage_Orden");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "OBJ_Orden" }, "UQ_LAB_Objective_General_Tenant_Version_Orden")
                        .IsUnique()
                        .HasFilter("[STG_IdStage] IS NULL");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "OBJ_Codigo" }, "UQ_LAB_Objective_SEG_IdTenant_LAB_IdVersion_OBJ_Codigo")
                        .IsUnique();

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "STG_IdStage", "OBJ_Orden" }, "UQ_LAB_Objective_Stage_Tenant_Version_Stage_Orden")
                        .IsUnique()
                        .HasFilter("[STG_IdStage] IS NOT NULL");

                    b.ToTable("LAB_Objective", null, t =>
                        {
                            t.HasCheckConstraint("CK_LAB_Objective_OBJ_Estatus", "[OBJ_Estatus] IN ('DRAFT', 'ACTIVE', 'INACTIVE')");

                            t.HasCheckConstraint("CK_LAB_Objective_OBJ_Orden", "[OBJ_Orden] > 0");

                            t.HasCheckConstraint("CK_LAB_Objective_OBJ_Peso", "[OBJ_Peso] > 0");

                            t.HasCheckConstraint("CK_LAB_Objective_OBJ_TipoEvidencia", "[OBJ_TipoEvidencia] IN ('CONVERSATION', 'USER_ACTION', 'ARTIFACT', 'DECISION', 'SYSTEM_RESULT')");
                        });
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Rubric", b =>
                {
                    b.Property<Guid>("RUB_IdRubric")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LAB_IdVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RUB_Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("RUB_Descripcion")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RUB_EscalaMaxima")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RUB_EscalaMinima")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RUB_Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("DRAFT");

                    b.Property<string>("RUB_InstruccionesEvaluador")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUB_MetodoCalculo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("RUB_Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RUB_PermiteFallaCritica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("RUB_RequiereEvidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("RUB_ScoreMinimoAprobacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RUB_TipoEvaluacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("RUB_VigenciaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RUB_VigenciaHasta")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SEG_IdTenant")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RUB_IdRubric");

                    b.HasAlternateKey("SEG_IdTenant", "LAB_IdVersion", "RUB_IdRubric")
                        .HasName("AK_LAB_Rubric_SEG_IdTenant_LAB_IdVersion_RUB_IdRubric");

                    b.HasIndex(new[] { "SEG_IdTenant", "RUB_Estatus" }, "IX_LAB_Rubric_SEG_IdTenant_RUB_Estatus");

                    b.HasIndex(new[] { "SEG_IdTenant", "RUB_TipoEvaluacion", "RUB_Estatus" }, "IX_LAB_Rubric_Tenant_Tipo_Estatus");

                    b.HasIndex(new[] { "SEG_IdTenant", "RUB_VigenciaDesde", "RUB_VigenciaHasta" }, "IX_LAB_Rubric_Tenant_Vigencias");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion" }, "UQ_LAB_Rubric_SEG_IdTenant_LAB_IdVersion")
                        .IsUnique();

                    b.HasIndex(new[] { "SEG_IdTenant", "RUB_Codigo" }, "UQ_LAB_Rubric_SEG_IdTenant_RUB_Codigo")
                        .IsUnique();

                    b.ToTable("LAB_Rubric", null, t =>
                        {
                            t.HasCheckConstraint("CK_LAB_Rubric_CreadoPor", "LEN(TRIM([CreadoPor])) > 0");

                            t.HasCheckConstraint("CK_LAB_Rubric_Escala", "[RUB_EscalaMaxima] > [RUB_EscalaMinima]");

                            t.HasCheckConstraint("CK_LAB_Rubric_RUB_Codigo", "LEN(TRIM([RUB_Codigo])) > 0");

                            t.HasCheckConstraint("CK_LAB_Rubric_RUB_Descripcion", "LEN(TRIM([RUB_Descripcion])) > 0");

                            t.HasCheckConstraint("CK_LAB_Rubric_RUB_EscalaMaxima", "[RUB_EscalaMaxima] = 10.00");

                            t.HasCheckConstraint("CK_LAB_Rubric_RUB_EscalaMinima", "[RUB_EscalaMinima] = 1.00");

                            t.HasCheckConstraint("CK_LAB_Rubric_RUB_Estatus", "[RUB_Estatus] IN ('DRAFT', 'APPROVED', 'PUBLISHED', 'RETIRED')");

                            t.HasCheckConstraint("CK_LAB_Rubric_RUB_InstruccionesEvaluador", "LEN(TRIM([RUB_InstruccionesEvaluador])) > 0");

                            t.HasCheckConstraint("CK_LAB_Rubric_RUB_MetodoCalculo", "[RUB_MetodoCalculo] IN ('WEIGHTED_AVERAGE', 'SIMPLE_AVERAGE', 'CRITICAL_GATE', 'WEIGHTED_WITH_CRITICAL_GATE')");

                            t.HasCheckConstraint("CK_LAB_Rubric_RUB_Nombre", "LEN(TRIM([RUB_Nombre])) > 0");

                            t.HasCheckConstraint("CK_LAB_Rubric_RUB_ScoreMinimoAprobacion", "[RUB_ScoreMinimoAprobacion] >= [RUB_EscalaMinima] AND [RUB_ScoreMinimoAprobacion] <= [RUB_EscalaMaxima]");

                            t.HasCheckConstraint("CK_LAB_Rubric_RUB_TipoEvaluacion", "[RUB_TipoEvaluacion] IN ('CONVERSATION', 'DESKTOP', 'HYBRID', 'ARTIFACT', 'MULTI_SOURCE')");

                            t.HasCheckConstraint("CK_LAB_Rubric_Vigencia", "([RUB_VigenciaHasta] IS NULL) OR ([RUB_VigenciaDesde] IS NULL) OR ([RUB_VigenciaHasta] >= [RUB_VigenciaDesde])");
                        });
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_RubricCriterion", b =>
                {
                    b.Property<Guid>("CRT_IdCriterion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CRT_Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("CRT_Descripcion")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRT_ErrorCritico")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CRT_EsCritico")
                        .HasColumnType("bit");

                    b.Property<string>("CRT_Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("DRAFT");

                    b.Property<string>("CRT_IndicadoresNegativos")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRT_IndicadoresPositivos")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CRT_Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CRT_Orden")
                        .HasColumnType("int");

                    b.Property<decimal>("CRT_Peso")
                        .HasPrecision(7, 4)
                        .HasColumnType("decimal(7,4)");

                    b.Property<string>("CRT_RecomendacionBase")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CRT_ScoreMinimoEsperado")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(7.00m);

                    b.Property<string>("CRT_TipoEvidencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LAB_IdVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MOM_IdExpectedMoment")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OBJ_IdObjective")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RUB_IdRubric")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SEG_IdTenant")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CRT_IdCriterion");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "MOM_IdExpectedMoment" }, "IX_LAB_RubricCriterion_Tenant_Version_Moment");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "OBJ_IdObjective" }, "IX_LAB_RubricCriterion_Tenant_Version_Objective");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "RUB_IdRubric" }, "IX_LAB_RubricCriterion_Tenant_Version_Rubric");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "RUB_IdRubric", "CRT_EsCritico" }, "IX_LAB_RubricCriterion_Tenant_Version_Rubric_EsCritico");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "RUB_IdRubric", "CRT_Estatus" }, "IX_LAB_RubricCriterion_Tenant_Version_Rubric_Estatus");

                    b.HasIndex(new[] { "SEG_IdTenant", "RUB_IdRubric", "CRT_Codigo" }, "UQ_LAB_RubricCriterion_Tenant_Rubric_Codigo")
                        .IsUnique();

                    b.HasIndex(new[] { "SEG_IdTenant", "RUB_IdRubric", "CRT_Orden" }, "UQ_LAB_RubricCriterion_Tenant_Rubric_Orden")
                        .IsUnique();

                    b.ToTable("LAB_RubricCriterion", null, t =>
                        {
                            t.HasCheckConstraint("CK_LAB_RubricCriterion_CRT_Codigo", "LEN(TRIM([CRT_Codigo])) > 0");

                            t.HasCheckConstraint("CK_LAB_RubricCriterion_CRT_Descripcion", "LEN(TRIM([CRT_Descripcion])) > 0");

                            t.HasCheckConstraint("CK_LAB_RubricCriterion_CRT_Estatus", "[CRT_Estatus] IN ('DRAFT', 'ACTIVE', 'INACTIVE')");

                            t.HasCheckConstraint("CK_LAB_RubricCriterion_CRT_IndicadoresPositivos", "LEN(TRIM([CRT_IndicadoresPositivos])) > 0");

                            t.HasCheckConstraint("CK_LAB_RubricCriterion_CRT_Nombre", "LEN(TRIM([CRT_Nombre])) > 0");

                            t.HasCheckConstraint("CK_LAB_RubricCriterion_CRT_Orden", "[CRT_Orden] > 0");

                            t.HasCheckConstraint("CK_LAB_RubricCriterion_CRT_Peso", "[CRT_Peso] > 0");

                            t.HasCheckConstraint("CK_LAB_RubricCriterion_CRT_ScoreMinimoEsperado", "[CRT_ScoreMinimoEsperado] >= 1.00 AND [CRT_ScoreMinimoEsperado] <= 10.00");

                            t.HasCheckConstraint("CK_LAB_RubricCriterion_CRT_TipoEvidencia", "[CRT_TipoEvidencia] IN ('CONVERSATION', 'USER_ACTION', 'ARTIFACT', 'DECISION', 'SYSTEM_RESULT', 'MULTIPLE')");

                            t.HasCheckConstraint("CK_LAB_RubricCriterion_CreadoPor", "LEN(TRIM([CreadoPor])) > 0");
                        });
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Stage", b =>
                {
                    b.Property<Guid>("STG_IdStage")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("LAB_IdVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SEG_IdTenant")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("STG_Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("STG_CondicionCompletitud")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STG_Descripcion")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("STG_EsObligatorio")
                        .HasColumnType("bit");

                    b.Property<string>("STG_Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("DRAFT");

                    b.Property<string>("STG_Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("STG_Orden")
                        .HasColumnType("int");

                    b.Property<bool>("STG_PermiteOrdenFlexible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("STG_TiempoSugeridoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("STG_TipoInteraccion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("STG_IdStage");

                    b.HasAlternateKey("SEG_IdTenant", "LAB_IdVersion", "STG_IdStage")
                        .HasName("AK_LAB_Stage_SEG_IdTenant_LAB_IdVersion_STG_IdStage");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion" }, "IX_LAB_Stage_SEG_IdTenant_LAB_IdVersion");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "STG_EsObligatorio" }, "IX_LAB_Stage_SEG_IdTenant_LAB_IdVersion_STG_EsObligatorio");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "STG_Estatus" }, "IX_LAB_Stage_SEG_IdTenant_LAB_IdVersion_STG_Estatus");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "STG_Codigo" }, "UQ_LAB_Stage_SEG_IdTenant_LAB_IdVersion_STG_Codigo")
                        .IsUnique();

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_IdVersion", "STG_Orden" }, "UQ_LAB_Stage_SEG_IdTenant_LAB_IdVersion_STG_Orden")
                        .IsUnique();

                    b.ToTable("LAB_Stage", null, t =>
                        {
                            t.HasCheckConstraint("CK_LAB_Stage_STG_Estatus", "[STG_Estatus] IN ('DRAFT', 'ACTIVE', 'INACTIVE')");

                            t.HasCheckConstraint("CK_LAB_Stage_STG_Orden", "[STG_Orden] > 0");

                            t.HasCheckConstraint("CK_LAB_Stage_STG_TiempoSugeridoMinutos", "([STG_TiempoSugeridoMinutos] IS NULL) OR ([STG_TiempoSugeridoMinutos] > 0)");

                            t.HasCheckConstraint("CK_LAB_Stage_STG_TipoInteraccion", "[STG_TipoInteraccion] IN ('CONVERSATION', 'DESKTOP', 'HYBRID', 'ARTIFACT')");
                        });
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_ExpectedMoment", b =>
                {
                    b.HasOne("HumanOS.SimulationLabs.Entities.LAB_LabVersion", "LabVersion")
                        .WithMany("ExpectedMoments")
                        .HasForeignKey("SEG_IdTenant", "LAB_IdVersion")
                        .HasPrincipalKey("SEG_IdTenant", "LAB_IdVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LAB_ExpectedMoment_LAB_LabVersion_SEG_IdTenant_LAB_IdVersion");

                    b.HasOne("HumanOS.SimulationLabs.Entities.LAB_Objective", "Objective")
                        .WithMany("ExpectedMoments")
                        .HasForeignKey("SEG_IdTenant", "LAB_IdVersion", "OBJ_IdObjective")
                        .HasPrincipalKey("SEG_IdTenant", "LAB_IdVersion", "OBJ_IdObjective")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LAB_ExpectedMoment_LAB_Objective_Tenant_Version_Objective");

                    b.HasOne("HumanOS.SimulationLabs.Entities.LAB_Stage", "Stage")
                        .WithMany("ExpectedMoments")
                        .HasForeignKey("SEG_IdTenant", "LAB_IdVersion", "STG_IdStage")
                        .HasPrincipalKey("SEG_IdTenant", "LAB_IdVersion", "STG_IdStage")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LAB_ExpectedMoment_LAB_Stage_Tenant_Version_Stage");

                    b.Navigation("LabVersion");

                    b.Navigation("Objective");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_LabVersion", b =>
                {
                    b.HasOne("HumanOS.SimulationLabs.Entities.LAB_Lab", "Lab")
                        .WithMany("Versiones")
                        .HasForeignKey("SEG_IdTenant", "LAB_IdLab")
                        .HasPrincipalKey("SEG_IdTenant", "LAB_IdLab")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LAB_LabVersion_LAB_Lab_SEG_IdTenant_LAB_IdLab");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Objective", b =>
                {
                    b.HasOne("HumanOS.SimulationLabs.Entities.LAB_LabVersion", "LabVersion")
                        .WithMany("Objectives")
                        .HasForeignKey("SEG_IdTenant", "LAB_IdVersion")
                        .HasPrincipalKey("SEG_IdTenant", "LAB_IdVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LAB_Objective_LAB_LabVersion_SEG_IdTenant_LAB_IdVersion");

                    b.HasOne("HumanOS.SimulationLabs.Entities.LAB_Stage", "Stage")
                        .WithMany("Objectives")
                        .HasForeignKey("SEG_IdTenant", "LAB_IdVersion", "STG_IdStage")
                        .HasPrincipalKey("SEG_IdTenant", "LAB_IdVersion", "STG_IdStage")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LAB_Objective_LAB_Stage_Tenant_Version_Stage");

                    b.Navigation("LabVersion");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Rubric", b =>
                {
                    b.HasOne("HumanOS.SimulationLabs.Entities.LAB_LabVersion", "LabVersion")
                        .WithOne("Rubric")
                        .HasForeignKey("HumanOS.SimulationLabs.Entities.LAB_Rubric", "SEG_IdTenant", "LAB_IdVersion")
                        .HasPrincipalKey("HumanOS.SimulationLabs.Entities.LAB_LabVersion", "SEG_IdTenant", "LAB_IdVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LAB_Rubric_LAB_LabVersion_SEG_IdTenant_LAB_IdVersion");

                    b.Navigation("LabVersion");
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_RubricCriterion", b =>
                {
                    b.HasOne("HumanOS.SimulationLabs.Entities.LAB_ExpectedMoment", "ExpectedMoment")
                        .WithMany("RubricCriteria")
                        .HasForeignKey("SEG_IdTenant", "LAB_IdVersion", "MOM_IdExpectedMoment")
                        .HasPrincipalKey("SEG_IdTenant", "LAB_IdVersion", "MOM_IdExpectedMoment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LAB_RubricCriterion_LAB_ExpectedMoment_Tenant_Version_Moment");

                    b.HasOne("HumanOS.SimulationLabs.Entities.LAB_Objective", "Objective")
                        .WithMany("RubricCriteria")
                        .HasForeignKey("SEG_IdTenant", "LAB_IdVersion", "OBJ_IdObjective")
                        .HasPrincipalKey("SEG_IdTenant", "LAB_IdVersion", "OBJ_IdObjective")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LAB_RubricCriterion_LAB_Objective_Tenant_Version_Objective");

                    b.HasOne("HumanOS.SimulationLabs.Entities.LAB_Rubric", "Rubric")
                        .WithMany("Criteria")
                        .HasForeignKey("SEG_IdTenant", "LAB_IdVersion", "RUB_IdRubric")
                        .HasPrincipalKey("SEG_IdTenant", "LAB_IdVersion", "RUB_IdRubric")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LAB_RubricCriterion_LAB_Rubric_Tenant_Version_Rubric");

                    b.Navigation("ExpectedMoment");

                    b.Navigation("Objective");

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Stage", b =>
                {
                    b.HasOne("HumanOS.SimulationLabs.Entities.LAB_LabVersion", "LabVersion")
                        .WithMany("Stages")
                        .HasForeignKey("SEG_IdTenant", "LAB_IdVersion")
                        .HasPrincipalKey("SEG_IdTenant", "LAB_IdVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LAB_Stage_LAB_LabVersion_SEG_IdTenant_LAB_IdVersion");

                    b.Navigation("LabVersion");
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_ExpectedMoment", b =>
                {
                    b.Navigation("RubricCriteria");
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Lab", b =>
                {
                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_LabVersion", b =>
                {
                    b.Navigation("ExpectedMoments");

                    b.Navigation("Objectives");

                    b.Navigation("Rubric");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Objective", b =>
                {
                    b.Navigation("ExpectedMoments");

                    b.Navigation("RubricCriteria");
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Rubric", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Stage", b =>
                {
                    b.Navigation("ExpectedMoments");

                    b.Navigation("Objectives");
                });
#pragma warning restore 612, 618
        }
    }
}
