// <auto-generated />
using System;
using HumanOS.SimulationLabs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanOS.SimulationLabs.Migrations
{
    [DbContext(typeof(SimulationLabsDbContext))]
    [Migration("20260912154159_CreateLabTable")]
    partial class CreateLabTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanOS.SimulationLabs.Entities.LAB_Lab", b =>
                {
                    b.Property<Guid>("LAB_IdLab")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LAB_Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LAB_Descripcion")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAB_Dominio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LAB_Estatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("LAB_Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("LAB_OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LAB_Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SEG_IdTenant")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LAB_IdLab");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_Estatus" }, "IX_LAB_Lab_SEG_IdTenant_LAB_Estatus");

                    b.HasIndex(new[] { "SEG_IdTenant", "LAB_Codigo" }, "UQ_LAB_Lab_SEG_IdTenant_LAB_Codigo")
                        .IsUnique();

                    b.ToTable("LAB_Lab", null, t =>
                        {
                            t.HasCheckConstraint("CK_LAB_Lab_LAB_Estatus", "[LAB_Estatus] IN ('DRAFT', 'PUBLISHED', 'RETIRED')");

                            t.HasCheckConstraint("CK_LAB_Lab_LAB_Tipo", "[LAB_Tipo] IN ('CONVERSATIONAL', 'DESKTOP', 'HYBRID')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
